FROM oven/bun

WORKDIR /app/client

# Build-time envs for Vite
ARG VITE_API_URL
ARG VITE_GOOGLE_CLIENT_ID

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID


COPY client/package.json client/bun.lock ./
RUN bun install

COPY client .


RUN bun run build

EXPOSE 5173

CMD ["bun", "run", "preview", "--host", "0.0.0.0", "--port", "5173"]
